### PR TITLE
[Fix #12842] Add new `Style/SendWithLiteralMethodName` cop

### LINKED ISSUE #12842: Cop Idea: Replace #send(LITERAL, ...) with method call
## Is your feature request related to a problem? Please describe.

In projects I've worked on, I've seen cases where `#send` was called with a literal symbol or string. This can come about due to heavy refactoring where the send was once more dynamic.

For example:

```rb
# bad
send(:puts)
send('puts')
obj.send(:nil?)
obj.send('nil?')

# good
puts
obj.nil?
```

## Describe the solution you'd like

A new cop that detects `#send(LITERAL, ...)` and replaces it with the method call named by the literal.

## Describe alternatives you've considered

The alternative is not implementing the cop and closing this issue. As I discover these by inspection, I manually fix them.

## Additional context

N/A

### PR DESCRIPTION
**Pull request by koic**
Fixes #12842.

## Summary

Detects the use of the `public_send` method with a literal method name argument. Since the `send` method can be used to call private methods, by default, only the `public_send` method is detected.

```ruby
# bad
obj.public_send(:method_name)
obj.public_send('method_name')

# good
obj.method_name
```

## Safety

This cop is not safe because it can incorrectly detect based on the receiver. Additionally, when `AllowSend` is set to `true`, it cannot determine whether the `send` method being detected is calling a private method.

## `AllowSend` option

This cop has `AllowSend` option.

### AllowSend: true (default)

```ruby
# good
obj.send(:method_name)
obj.send('method_name')
obj.__send__(:method_name)
obj.__send__('method_name')
```

### AllowSend: false

```ruby
# bad
obj.send(:method_name)
obj.send('method_name')
obj.__send__(:method_name)
obj.__send__('method_name')

# good
obj.method_name
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by Earlopain** [comment]
I don't think this cop should concern itself with constants (at least by default). Surely I used a constant to intentionally factor it out, unless the constant is referenced only once I'd want to keep it.

**Comment by koic** [comment]
Since a constant is generally immutable by definition, I think it can always be targeted without needing options. Are there any valid cases for excluding a constant?

**Comment by Earlopain** [comment]
There are barely any cases I could find that use `public_send` over `send` for this (send is just so much more used). This is basically what I was thinking about: https://github.com/hopsoft/turbo_boost-commands/blob/9b4535ca0fe17481e70ae292d03db5b3e984d376/test/application_system_test_case.rb#L11

It uses a constant to have one place that holds which browser is being tested. I don't believe the code will improve by calling the method directly.

**Comment by koic** [comment]
> I don't believe the code will improve by calling the method directly.

I see! Since using constants is intentional in some cases, it seems better to respect the user's intent and continue to target only string literals and symbol literals as is.

> I'm not sure about the name.

The cop name `Style/StaticSend` has been updated to `Style/SendWithLiteralMethodName`.

**Pull request merged**
