### PR TITLE
Add new `Style/RedundantArrayConstructor` cop

### PR DESCRIPTION
**Pull request by koic**
Follow up https://github.com/rubocop/rubocop/pull/11874#issuecomment-1550911537.

Checks for the instantiation of array using redundant `Array` constructor. Autocorrect replaces to array literal which is the simplest and fastest.

```ruby
# bad
Array.new([])
Array[]
Array([])
Array.new(['foo', 'foo', 'foo'])
Array['foo', 'foo', 'foo']
Array(['foo', 'foo', 'foo'])

# good
[]
['foo', 'foo', 'foo']
Array.new(3, 'foo')
Array.new(3) { 'foo' }
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by fatkodima** [comment]
I think a similar cop can be created for a string too?

**Comment by bbatsov** [comment]
Btw, for arrays the constructor is redundant also when you're just enumerating some elements, as you can use a literal directly then. Not sure if it's worth covering this here or separately, though.

**Comment by koic** [comment]
> Btw, for arrays the constructor is redundant also when you're just enumerating some elements, as you can use a literal directly then. 

My understanding hasn't quite caught up 💦  Can you provide an example code?

**Comment by koic** [comment]
> I think a similar cop can be created for a string too?

It seems like that case would be handled by `Performance/UnfreezeString`.
https://docs.rubocop.org/rubocop-performance/cops_performance.html#performanceunfreezestring

**Comment by bbatsov** [comment]
@koic I was thinking of:

```ruby
arr = Array[1, 2, 3]
```

Not exactly a classic constructor, but I guess you get the idea.

**Comment by koic** [comment]
Ah I didn't realize that. I think `Array([1, 2, 3])` can be handled similarly. I updated this PR to handle them.

**Comment by bbatsov** [comment]
Looks great now. Thanks!

**Pull request merged**
