### PR TITLE
Add `rubygems_version` and `specification_version` as deprecated attributes to `Gemspec/DeprecatedAttributeAssignment`

### PR DESCRIPTION
**Pull request by kaitithoma**
These changes are made in order to check for `rubygems_version` and `specification_version` assignment in a gemspec file. RubyGems source says not to use them (https://github.com/rubygems/rubygems/blob/cc6f96aa0c1c99d94363d12884001a2de28da033/lib/rubygems/specification.rb#L530-L534
https://github.com/rubygems/rubygems/blob/cc6f96aa0c1c99d94363d12884001a2de28da033/lib/rubygems/specification.rb#L744-L748)

> DO NOT set this, it is set automatically when the gem is packaged.

These checks are integerated into Gemspec/DeprecatedAttributeAssignment as suggested in [#10634](https://github.com/rubocop/rubocop/pull/10634)
```ruby
# bad
Gem::Specification.new do |spec|
  spec.name = 'your_cool_gem_name' 
  spec.rubygems_version = 2.5
end

# good
Gem::Specification.new do |spec|
  spec.name = 'your_cool_gem_name'
end
```
```ruby
# bad
Gem::Specification.new do |spec|
  spec.name = 'your_cool_gem_name'
  spec.spcification_version = 2.5
end

# good
Gem::Specification.new do |spec|
  spec.name = 'your_cool_gem_name'
end
```
-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
The changes look good, but your branch has to be rebased on top of the current `master` branch due to merge conflicts.

In hindsight probably we should had bucketed all such attributes in the same cop, instead of having one cop per each attribute, but that ship has sailed. I hope those are the final cops on this topic. :-)

**Comment by nobuyo** [comment]
Looks like the changelog entry file have not been added 👀

**Comment by kaitithoma** [comment]
> The changes look good, but your branch has to be rebased on top of the current `master` branch due to merge conflicts.
> 
> In hindsight probably we should had bucketed all such attributes in the same cop, instead of having one cop per each attribute, but that ship has sailed. I hope those are the final cops on this topic. :-)

Could I try to disable `Gemspec/DateAssignment` and add some new cop (maybe `GemspecAttributeAssignment`) or having 3 different cops is better than that?

**Comment by koic** [comment]
The already released `Gemspec/DateAssignment` can be integrated in the future. However that integration is pending as breaking changes cannot be made in RuboCop 1.x. Anyway, I think these cops will be able to integrate into the cop of #10643. Please wait a moment.

**Comment by bbatsov** [comment]
https://github.com/rubocop/rubocop/pull/10643 has been merged.

**Comment by kaitithoma** [comment]
I updated this PR (including title and initial comment). However, I see there is a relevant open issue ([#10675](https://github.com/rubocop/rubocop/issues/10675))

**Comment by bbatsov** [comment]
@kaitithoma Thanks! We'll address the open issue separately.

**Pull request merged**
