### PR TITLE
[Fix #10918] Add `<<` to `Style/StringConcatenation`

### LINKED ISSUE #10918: Add Style/StringConcatenation support for << with string literals?
`Style/StringConcatenation` cop detects string concatenation using `+` like so:

```ruby
'hello ' + name
# corrects to interpolation:
"hello #{name}"
```

It seems this cop could also detect concatenation using `<<` in a similar way if the left-hand operand is a literal:
```ruby
'hello ' << name
# would also correct to:
"hello #{name}"
```

### PR DESCRIPTION
**Pull request by HeroProtagonist**
Closes #10918

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by HeroProtagonist** [comment]
Causes internal lints. Perhaps the cop should have this added as a config option with default false?

**Comment by bbatsov** [comment]
Hmm, I thought that `+` and `<<`/`concat` had different semantics (new string vs modifying the receiver), but I guess this is OK for the current cop. 

> Causes internal lints. Perhaps the cop should have this added as a config option with default false?

It's fine to also update the existing code.

**Comment by bbatsov** [comment]
I wonder if we should also handle `concat` is some way, but probably that'd be an overkill.

**Comment by HeroProtagonist** [comment]
I realized that the rule is only valid if the receiver is a string. Right now I made it check both left and right hand sides which is wrong. When I correct this, the internal lints will no longer be flagged.


```ruby
[] << "foo" # not string concatenation

"#{[]}foo" # currently would yield an invalid correction
```

The issue mentioned this, but I missed it 🤦  
> It seems this cop could also detect concatenation using << in a similar way if the left-hand operand is a literal

**Comment by vlad-pisanov** [comment]
@HeroProtagonist thanks for taking a look at this, but now I realize this substitution would be unsafe. 😞 Even if the receiver is a string literal, `<<` cannot be replaced with interpolation if the operand is a number:

```ruby
op = 65

"hello " << op    # "hello A"
"hello #{op}"     # "hello 65"
```

`<<` turns numbers into the corresponding ascii character, while interpolation turns them into decimal representation

**Comment by bbatsov** [comment]
So, what are we doing with this one?

**Comment by HeroProtagonist** [comment]
I don't think this should be added as it only applies in a few cases. Thoughts @vlad-pisanov?

**Comment by bbatsov** [comment]
I'll take the lack of activity here as an indication we've decided to abandon this.

**Pull request closed without merging**
