### PR TITLE
Use CodeSpell GitHub Action

### PR DESCRIPTION
**Pull request by nschonni**
The project offers a GitHub Action directly, so swapping out the custom PIP install setup

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [ ] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [ ] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [ ] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [ ] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
Thanks!

**Comment by bbatsov** [comment]
@nschonni I've noticed that the new action tends to get stuck (it didn't finish for any PR since yesterday). Can you please look into this?

**Comment by nschonni** [comment]
Can you point to where it's stalling out, I'm not seeing any on https://github.com/rubocop/rubocop/actions/workflows/spell_checking.yml

**Comment by nschonni** [comment]
If you mean stalled like on https://github.com/rubocop/rubocop-minitest/pull/246, that's related to the branch rules looking for a name related to the old job name `
Check spelling of all files with codespell (3.8)` rather than the the new one

**Comment by bbatsov** [comment]
It seemed to have stalled here when I was looking at this PR, but now I see it seemed to have passed https://github.com/rubocop/rubocop/actions/runs/4464137982/jobs/7840005670 Anyways, not a big deal - I'll keep an eye out for this.

**Comment by ydah** [comment]
It looks like there is a job that never ends, probably because an old spell check job is specified as a required job, although it is also occurring below.

- https://github.com/rubocop/rubocop/pull/11718

image

**Comment by koic** [comment]
I've removed old workflow from status checks that are required. So, that issue has been resolved.

**Pull request merged**
