### PR TITLE
Replace forwardable with explicit delegation for performance

### PR DESCRIPTION
**Pull request by Earlopain**
I'm doing performance profiling and was surprised for these to appear at all in the samples. Here are some numbers (3 warmup runs, 20 measured runs, cache used)::

```
# with forwardable in both rubocop + rubocop-ast
$ hyperfine -w 3 -r 20 "bundle exec rubocop Rakefile"
Benchmark 1: bundle exec rubocop Rakefile
  Time (mean ± σ):      1.169 s ±  0.016 s    [User: 0.976 s, System: 0.190 s]
  Range (min … max):    1.138 s …  1.198 s    20 runs

# with forwardable only in rubocop-ast
$ hyperfine -w 3 -r 20 "bundle exec rubocop Rakefile"
Benchmark 1: bundle exec rubocop Rakefile
  Time (mean ± σ):      1.145 s ±  0.011 s    [User: 0.959 s, System: 0.185 s]
  Range (min … max):    1.131 s …  1.170 s    20 runs

# with forwardable in neither
$ hyperfine -w 3 -r 20 "bundle exec rubocop Rakefile"
Benchmark 1: bundle exec rubocop Rakefile
  Time (mean ± σ):      1.136 s ±  0.020 s    [User: 0.950 s, System: 0.183 s]
  Range (min … max):    1.098 s …  1.168 s    20 runs
```

Overall ~ 3% faster

-------

Full run, also about 3%:

```
# with forwardable in both rubocop + rubocop-ast
$ hyperfine -w 3 -r 20 "bundle exec rubocop"
Benchmark 1: bundle exec rubocop
  Time (mean ± σ):      1.704 s ±  0.018 s    [User: 1.903 s, System: 1.004 s]
  Range (min … max):    1.669 s …  1.742 s    20 runs

# with forwardable only in rubocop-ast
$ hyperfine -w 3 -r 20 "bundle exec rubocop"
Benchmark 1: bundle exec rubocop
  Time (mean ± σ):      1.677 s ±  0.025 s    [User: 1.847 s, System: 0.988 s]
  Range (min … max):    1.640 s …  1.763 s    20 runs

# with forwardable in neither
$ hyperfine -w 3 -r 20 "bundle exec rubocop"
Benchmark 1: bundle exec rubocop
  Time (mean ± σ):      1.656 s ±  0.020 s    [User: 1.817 s, System: 0.984 s]
  Range (min … max):    1.630 s …  1.700 s    20 runs
```

Companion PR for `rubocop-ast`: https://github.com/rubocop/rubocop-ast/pull/312

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [ ] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by koic** [comment]
This might be sufficient if the abstraction provided for unknown methods is not needed.

**Comment by marcandre** [comment]
So indeed it looks like `forwardable` [executes extra code](https://github.com/ruby/ruby/blob/master/lib/forwardable.rb#L203) than what is necessary.

1) Has there ever been a feature request opened on ruby-core for a `minimal: true` option or similar to `def_delegate`?
2) Why don't we instead make our own `forwardable` clone that only does the forwarding?

**Comment by Earlopain** [comment]
> This might be sufficient if the abstraction provided for unknown methods is not needed.

Can you elaborate? I don't know what you mean with that.

> Has there ever been a feature request...

I searched through the bugtracker and haven't found something. It did remind me that ruby has thoughs about making `forwardable` a bundled gem though... I commented on the issue for that. Not a fan

> Why don't we instead make our own...

I honestly don't see much value in that. Few places really _need_ it, delegating numerous methods. Most just do one or two which I think is fine to expliciy type out. But if you insist I will amend the PR.

**Comment by marcandre** [comment]
> suffici



> > Why don't we instead make our own...
> 
> I honestly don't see much value in that. Few places really _need_ it, delegating numerous methods. Most just do one or two which I think is fine to expliciy type out. But if you insist I will amend the PR.

I do find the older code clearer than the new one. It was using a simple abstraction explicitly. We already have the code (the `class_eval`), we just need to extract it to a helper function.

**Comment by Earlopain** [comment]
> I do find the older code clearer

That's fair, I don't feel too strongly myself. I will amend the ast PR later when I got a bit more time and offer something similar here

**Comment by marcandre** [comment]
Great, thank you so much @Earlopain . Let me know if you'd prefer I do it.

**Comment by Earlopain** [comment]
Please do, you probably have something in mind already. I'm not sure where to put. You should be able to edit my branch if you want, or just make it from scratch if you prefer.

**Pull request merged**
