### PR TITLE
[Fix #10586] Fix a false positive for `Style/DoubleNegation`

### LINKED ISSUE #10586: Style/DoubleNegation allowed_in_returns doesn't take into account `define_method` and `define_singleton_method`
--------

## Expected behavior

The default rubocop configuration shouldn't return errors when using `!!` in the return of a `define_method`/`define_singleton_method`

## Actual behavior

rubocop reports an error:

```
a.rb:2:3: C: [Correctable] Style/DoubleNegation: Avoid the use of double negation (!!).
  !!good
  ^
a.rb:6:3: C: [Correctable] Style/DoubleNegation: Avoid the use of double negation (!!).
  !!bad
  ^
```

## Steps to reproduce the problem

```ruby
define_method :good? do
  !!good
end

define_singleton_method :bad? do
  !!bad
end
```

## RuboCop version

```
1.27.0 (using Parser 3.1.2.0, rubocop-ast 1.17.0, running on ruby 3.1.2 x86_64-darwin21)
```

### PR DESCRIPTION
**Pull request by ydah**
Fixes: #10586

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
I'd also update the code examples to mention explicitly `define_method` and `define_singleton_method`.

**Comment by dorianmariefr** [comment]
Awesome, maybe it could work also for `self.class.define_method`

**Comment by ydah** [comment]
I add code examples `define_method` and `define_singleton_method`.
I updated this PR! Thank you so much!

**Comment by bbatsov** [comment]
Thanks!

**Pull request merged**
