### PR TITLE
Add new `Style/FileWrite` cop

### PR DESCRIPTION
**Pull request by leoarnold**
In his 2016 talk ["Little Snippets"](https://youtu.be/mC9TyVeER_8?t=560) Xavier Noria (@fxn) points out that Ruby 1.8 had the idiom

```ruby
File.open(filename, 'w') do |f|
  f.write(content)
end
```

whereas starting with Ruby 1.9 this can be replaced with

```ruby
File.write(filename, content)
```

This commit introduces the `Style/FileWrite` cop which investigates
said offense and similar cases where the convenience methods
`File.write` or `File.binwrite` can be used.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
I like the proposal. It'd be good to cover this and your other suggestion in the Ruby style guide as well.

**Comment by leoarnold** [comment]
@bbatsov Done: https://github.com/rubocop/ruby-style-guide/pull/890

**Comment by dvandersluis** [comment]
Thanks for making the changes I proposed on #10261 here as well! Now that there basically is the same structure to the two cops, we should probably extract the shared code out to a shared mixin. You could use arguments for the file mode sets and method name (see https://docs.rubocop.org/rubocop-ast/node_pattern.html#for-arguments).

**Comment by leoarnold** [comment]
@dvandersluis Is it really worth it to extract the methods? So far, both cops are self-contained and I cannot envision future cops to make use of the extracted method. As far as I can see, it would just create unnecessary cohesion.

**Comment by dvandersluis** [comment]
@leoarnold it's not mandatory, but it is a pattern we tend to follow when we would otherwise have duplicated code. `FileRead` and `FileWrite` here are very similar cops so I think it makes sense.

**Comment by bbatsov** [comment]
The changes look good, but your branch has to be rebased on top of the current `master` branch due to merge conflicts. I'm ambivalent towards the duplicated code, as we can address this down the road as well.

**Comment by bbatsov** [comment]
Thanks!

**Pull request merged**
