### PR TITLE
Reorganize RuboCop help into sections for better clarity

### PR DESCRIPTION
**Pull request by dvandersluis**
As demonstrated [here](https://github.com/rubocop/rubocop-rspec/issues/1189#issuecomment-926087648) for example, we have a *lot* of CLI options, and they're not always easily findable or understandable from `--help`. This is not very friendly for RuboCop beginners, in particular.

This change reorganizes the options into logical groups, does some minor rewording of options I thought were a bit unclear, and also adds some basic colouring (the section headings are made bright).

image
(This is some, but not nearly all, of the help)

Happy to take any suggestions for further rewording, different ordering of sections or within sections (I tried to make it flow logically), etc.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by dvandersluis** [comment]
Related general question: is it time to make the lines in `--help` longer? They're roughly trimmed to ~85 characters, but it makes `--help` very tall.

**Review by bbatsov — APPROVED** [review]
Nicely done! I think it's fine to stick with the current text wrapping, as I'm not sure how longer text will look in (real) text consoles.

**Comment by dvandersluis** [comment]
Apparently I forgot to add a change logitem for this 🤔

**Comment by bbatsov** [comment]
You can just edit the changelog end the release notes directly.

**Pull request merged**
