### PR TITLE
[Fix #8469] Add cop Layout/SpaceAroundSingletonClassOperator

### LINKED ISSUE #8469: New cop: Layout/SpaceAroundSingletonInheritence
## Is your feature request related to a problem? Please describe.

One could write

```ruby
class<<self
```

which isn't as readable as adding spaces around the `<<` operator:

```ruby
class << self
```

## Describe the solution you'd like

There should be a layout cop that checks whether there are spaces around the `<<` operator for singleton class inheritence.

## Describe alternatives you've considered

-

## Additional context

-

### PR DESCRIPTION
**Pull request by jonas054**
I chose the name `SpaceAroundSingletonClassOperator` rather than `SpaceAroundSingletonInheritence`, which was suggested in the feature request. Although I'm not sure that `<<` is actually an operator, I am pretty sure that inheritance is not involved. The operator (for lack of a better term) opens up the singleton class, or eigenclass, so methods can be added to it.

### CODE REVIEW

**Comment by koic** [comment]
IMO, it would be better for `Layout/SpaceAroundOperators` to be aware of sclass `<<` operator rather than adding a new cop. Also, it seems that there is no need to make new `no_space` option for the operator.
https://github.com/rubocop/rubocop/blob/v1.18.2/lib/rubocop/cop/layout/space_around_operators.rb

**Comment by jonas054** [comment]
I guess you're right. I'll add it to the existing cop.

**Comment by jonas054** [comment]
I'm not sure what I need to do in order to stick to the semantic versioning rules. A new cop is marked as `pending` until the next major release of RuboCop, but what about breaking changes like this one, where we want to add more inspection duties to an existing cop? Ideally we'd want those changes to not come into effect until the next major release.

I'm not aware of any mechanism to make the feature pending. Is it enough to mark it as Breaking in the change log?

**Comment by koic** [comment]
`Layout/SpaceAroundOperators`'s role is to check that operators have space around them. Therefore I think it is not a breaking change because it can be considered a false negative of `Layout/SpaceAroundOperators`.

**Comment by jonas054** [comment]
Closing this PR to open a new one with the bug fix approach when I'm done.

**Pull request closed without merging**
