### PR TITLE
ci: add GitHub token permissions for workflows

### PR DESCRIPTION
**Pull request by varunsh-coder**
This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using https://github.com/step-security/secure-workflows.

GitHub recommends defining minimum GITHUB_TOKEN permissions for securing GitHub Actions workflows 
- https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/  
- https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
- The Open Source Security Foundation (OpenSSF) [Scorecards](https://github.com/ossf/scorecard) treats not setting token permissions as a high-risk issue 

This project is part of the top 100 critical projects as per OpenSSF (https://github.com/ossf/wg-securing-critical-projects), so fixing the token permissions to improve security.

Before the change:
`GITHUB_TOKEN` has `write` permissions for multiple scopes, e.g. 
https://github.com/rubocop/rubocop/runs/7939389109?check_suite_focus=true#step:1:19

After the change:
`GITHUB_TOKEN` will have minimum permissions needed for the jobs. 

Signed-off-by: Varun Sharma <varunsh@stepsecurity.io>

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed related commits together.
* [ ] Added tests.
* [ ] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [ ] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
@rubocop/rubocop-core Anyone familiar with these token permissions to provide a review?

**Comment by koic** [comment]
There seem to be some similar PRs opened and I found a discussion at Node.js repository.
https://github.com/nodejs/node/pull/43743

It seems that there are pros and cons, and it is difficult for me to judge whether or not to merge this. And I have no curiosity and opinion about this yet.

**Comment by bbatsov** [comment]
> Please let me know if you have any questions about this. I am also curious what is the con that you see with this change?Thanks!

I don't see any cons, I'm just wary of breaking something by doing changes we don't fully understand. Anyways, I've reviewed your suggestion and the links you've provided and everything looks good to me. Can you rebase on top of `master` to address the merge conflict?

**Comment by varunsh-coder** [comment]
> @varunsh-coder ping :-)

Sorry for the delay. I will do this today.

**Comment by varunsh-coder** [comment]
> > @varunsh-coder ping :-)
> 
> Sorry for the delay. I will do this today.

Done.

**Comment by bbatsov** [comment]
Thanks!

**Pull request merged**
