### PR TITLE
[Fix #11338] Add new `Style/ComparableClamp` cop

### LINKED ISSUE #11338: New cop idea: Use Comparable#clamp, Array#{min,max} instead of comparison operators
## Is your feature request related to a problem? Please describe.

Today I suggested using `Comparable#clamp` instead of comparison operators in a private project, like the following.

```ruby
# bad - I feel it's not readable...
user_input > threshold ? threshold : user_input

# good - I can imagine the intention of this code easily!
user_input.clamp(..threshold)
```

I think RuboCop can aid with this problem, but there is no cop to detect this problem.

## Describe the solution you'd like

Add a cop to detect the comparison operators' usage. The cop suggests `user_input.clamp(..threshold)` instead of comparison operators.

### `Array#min`

The following code has the same meaning as the above example also.

```ruby
[user_input, threshold].min
```

Which of these is appropriate depends on the situation. If one of the values is a threshold, `clamp` clarifies the intention. But if both values are user inputs, `min` is better than `clamp`.

```ruby
# It's good
[user_input_a, user_input_b].min

# It's strange...
user_input_a.clamp(..user_input_b)
```

Therefore I think the cop should suggest both `min` and `clamp`.

### `Array#max` and `a.clamp(x..y)`

By the way, the cop can detect cases for `Array#max` and `clamp(lower_threshold..upper_threhold)` (or `clamp(lower_threshold, upper_threhold)`).

## Describe alternatives you've considered

nothing

## Additional context

There are performance differences between comparison operators, `clamp`, and `min`.

```ruby
require 'benchmark/ips'

require 'benchmark'
Benchmark.ips do |x|
  a = 42
  b = 43

  x.report('ops') { a > b ? b : a }
  x.report('min') { [a, b].min }
  x.report('clamp') { a.clamp(..b) }

  x.compare!
end
```

```console
$ ruby -v rubocop-clamp-min-performance.rb
ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin21]
Warming up --------------------------------------
                 ops     2.035M i/100ms
                 min     2.203M i/100ms
               clamp   879.718k i/100ms
Calculating -------------------------------------
                 ops     20.230M (± 1.4%) i/s -    101.765M in   5.031438s
                 min     21.694M (± 1.5%) i/s -    110.157M in   5.078819s
               clamp      8.694M (± 1.9%) i/s -     43.986M in   5.060963s

Comparison:
                 min: 21694180.2 i/s
                 ops: 20229721.8 i/s - 1.07x  (± 0.00) slower
               clamp:  8694430.4 i/s - 2.50x  (± 0.00) slower
```

Operators and `min` have almost the same speed because the VM executes `min` with an Array literal as an optimized instruction (`opt_newarray_min`).

```console
$ ruby --dump=insns -e '[a,b].min'
== disasm: #<ISeq:<main>@-e:1 (1,0)-(1,9)> (catch: false)
0000 putself                                                          (   1)[Li]
0001 opt_send_without_block                 <calldata!mid:a, argc:0, FCALL|VCALL|ARGS_SIMPLE>
0003 putself
0004 opt_send_without_block                 <calldata!mid:b, argc:0, FCALL|VCALL|ARGS_SIMPLE>
0006 opt_newarray_min                       2
0008 leave
```

I think this difference does not affect the entire application's performance. Probably it's a good idea that the document mention the performance.

### PR DESCRIPTION
**Pull request by koic**
## Summary

Fixes #11338.

This PR adds new `Style/ComparableClamp` cop.
It enforces the use of `Comparable#clamp` instead of comparison by minimum and maximum.

```ruby
# bad
[[x, low].max, high].min

# bad
if x < low
  low
elsif high < x
  high
else
  x
end

# good
x.clamp(low, high)
```

This cop supports autocorrection for `if/elsif/else` bad style only.
Because `ArgumentError` occurs if the minimum and maximum of `clamp` arguments are reversed.
When these are variables, it is not possible to determine which is the minimum and maximum:

```ruby
[1, [2, 3].max].min # => 1
1.clamp(3, 1)       # => min argument must be smaller than max argument (ArgumentError)
```

## Additional Information

- `Comparable#clamp` was introduced in Ruby 2.4
- Part of #11338 was implemented by #11341

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by pocke** [comment]
```ruby
if a < low
  low
elsif high < a
  high
else
  a
end
```

This cop can detect the above code too. Do you have the plan to implement it?

**Comment by koic** [comment]
I had overlooked that cases. I will take it in this PR.

**Comment by koic** [comment]
I've updated the entire PR. In particular, this cop's autocorrection strategy has changed and is documented in this PR and cop description.

**Comment by bbatsov** [comment]
Looks good to me. I had completely forgotten about `clamp`, and I guess I'm not the only one. We should look in the newer Ruby APIs and potentially come up with other similar cops that can promote them.

**Pull request merged**
