### PR TITLE
Support Ruby 3.1's hash value omission for `Style/HashSyntax`

### PR DESCRIPTION
**Pull request by koic**
## Summary

Ruby 3.1 will be introduced hash shorthand syntax:
https://bugs.ruby-lang.org/issues/17292.

The `EnforcedShorthandSyntax` option checks hash literal value.
It can enforce either the use of the explicit hash value syntax or the use of Ruby 3.1 hash value shorthand syntax (when applicable).

A separate offense is registered for each problematic hash literal value.

The option values are:

* always - forces use of the 3.1 syntax (e.g. `{foo:}`) when the hash key and value are the same.
* never - forces use of explicit hash literal value

```ruby
# EnforcedShorthandSyntax: always (default)

# bad
{foo: foo, bar: bar}

# good
{foo:, bar:}

# EnforcedShorthandSyntax: never

# bad
{foo:, bar:}

# good
{foo: foo, bar: bar}
```

## Additional Information

This cop is based on the upgrade from ES5 to ES6 with ESLint.

The ES6 shorthand syntax is chosen by default for ESLint shorthands:

> "always" (default) expects that the shorthand will be used whenever possible.

https://eslint.org/docs/rules/object-shorthand

The cop will also choose the new Ruby 3.1 shorthand syntax by default.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by koic** [comment]
And I opened a PR to The Ruby Style Guide.
https://github.com/rubocop/ruby-style-guide/pull/892

**Comment by bbatsov** [comment]
Won't it be better to just add a boolean `use_shorthand_syntax` option (or something like this) to the existing `HashSyntax` cop? It seems like an overkill to add a separate cop for this.

**Comment by koic** [comment]
Ah, that makes sense to me! I updated this PR.

And I added `EnforcedShorthandSyntax` to `Style/HashSyntax` instead of `UseShorthandSyntax`.
This is because if the option requires a trivalue like `mixed` (string value type) in the future, the type will be unmatched with `UseShorthandSyntax` which accepts `true` or` false` (boolean value type).

**Comment by bbatsov** [comment]
Good idea! Thanks!

**Pull request merged**
