### PR TITLE
Add ability to profile rubocop execution via `--profile` and `--memory` options

### PR DESCRIPTION
**Pull request by fatkodima**
As per discussion -  https://github.com/rubocop/rubocop/pull/11326#issuecomment-1364477250

With these changes, users will be able to easily profile rubocop within their projects (and possibly send PRs with improvements or report back identified performance problems).

Example usage:
```
rubocop --profile --memory
```

`--profile` - will do a CPU profiling (via `stackprof`) and create a dump file within `tmp` directory of the project's root
`--memory` - will additionally profile memory usage (via `memory_profiler`) and create a memory profiling info file within same `tmp` directory

### CODE REVIEW

**Comment by fatkodima** [comment]
Tests are passing on my machine (Mac OS), but are failing on CI (Windows). Would appreciate if someone suggest why.

**Comment by fatkodima** [comment]
The problem was that `stackprof` does not support windows - https://github.com/tmm1/stackprof/issues/45.

@bbatsov @koic Can you take a look at this PR?

**Comment by bbatsov** [comment]
@fatkodima Might be good to document somewhere how to profile RuboCop with the built-in options.

**Comment by fatkodima** [comment]
Added some docs. Writing docs is not my strong skill, sorry 😄

**Comment by bbatsov** [comment]
Don't worry. This will do for start. Thanks!

**Pull request merged**
