### PR TITLE
Add ArrayAlignment to list of recommended Layout cops for LineLength

### PR DESCRIPTION
**Pull request by jdufresne**
Both ArgumentAlignment and HashAlignment are listed so it looks like
ArrayAlignment should also be included.

### CODE REVIEW

**Comment by koic** [comment]
Can you update https://github.com/rubocop/rubocop/blob/v1.33.0/lib/rubocop/cop/layout/line_length.rb#L8-L61 instead of updating docs/modules/ROOT/pages/cops_layout.adoc directly. docs/modules/ROOT/pages/cops_layout.adoc is auto-generated, so don't change it.

**Comment by koic** [comment]
@jdufresne ping.

**Comment by jdufresne** [comment]
> Can you update https://github.com/rubocop/rubocop/blob/v1.33.0/lib/rubocop/cop/layout/line_length.rb#L8-L61 instead of updating docs/modules/ROOT/pages/cops_layout.adoc directly. docs/modules/ROOT/pages/cops_layout.adoc is auto-generated, so don't change it.

Thanks for the review. I've made this change in the latest revision.

**Comment by koic** [comment]
Thanks!

**Pull request merged**
