### PR TITLE
Add ExtraSpacing cop that detects unnecessary whitespace.

### LINKED ISSUE #1434: UnnecessarySpaceCharacter
Apologies in advance if this already exists.

When it comes to code styling, at Ennova, we prefer to remove unnecessary whitespace from our code.
Things such as additional spaces just to line up some expectations, or assignments, we consider undesirable.

> **Prefer this:**
> 
> ``` ruby
>          expect(subject.pdfkit.options['--margin-bottom']).to eq '13mm'
>          expect(subject.pdfkit.options['--margin-left']).to eq '14mm'
>          expect(subject.pdfkit.options['--margin-right']).to eq '15mm'
> ```
> 
> **Instead of this:**
> 
> ``` ruby
>          expect(subject.pdfkit.options['--margin-bottom']).to  eq '13mm'
>          expect(subject.pdfkit.options['--margin-left']).to    eq '14mm'
>          expect(subject.pdfkit.options['--margin-right']).to   eq '15mm'
> ```

I'm not sure if this is indicative of other ruby codebases, but other than indentation and inside strings, I don't really see a case where we would use 2 spaces characters, right after each other.

I propose a Cop (which the user can opt in to using) that when run over the following example would raise issue on the noted line:

> **Code example**

``` ruby
describe 'examples' do
  it "shouldn't alert a cop" do
    expect('this').to eq 'this'
    expect('this  this').to eq 'this  this'
  end

  it "should alert a cop" do
    expect('this').to      eq 'this' # raises issue on this line
  end
end
```

> **Expectation**

```
test.rb:7:6: C: Unnecessary space characters used. 
expect('this').to      eq 'this' # raises issue on this line
                 ^^^^^^

1 file inspected, 1 offense detected
```

### PR DESCRIPTION
**Pull request by bayleedev**
Fixes #1434 and #1450

### CODE REVIEW

**Comment by bradleypriest** [comment]
Are there plans to add options to this? I really like lining up my assignments

**Comment by bquorning** [comment]
@bradleypriest The code in #1654 has not been released yet, but it allows you to configure an array of operators that may be surrounded by multiple spaces. But then again, the actual *checking* of multiple spaces around operators also isn’t released yet.

If that doesn’t solve it, could you please open a separate issue describing your problem?

**Comment by bradleypriest** [comment]
@bquorning I just realized what I'm wanting is actually almost impossible to separate from this and not what I originally thought.

Basically allowing this not to throw extra whitespace errors
```ruby
Widget = Class.new(Gecko::Record::Base) do
  attribute :name,       String
  attribute :secret,     String
  attribute :score,      BigDecimal
  attribute :started_on, Date
  attribute :started_at, DateTime
  attribute :wodgets,    Array[Wodget]
end
```

**Comment by u2** [comment]
```ruby
result = message.is_a?(String) ?  { error: message } : message
`

**Comment by jonas054** [comment]
@u2 Note that this cop is disabled by default. You need to add
```yaml
Style/ExtraSpacing:
  Enabled: true
```
in your `.rubocop.yml`.

I agree about CHANGELOG, so I've pushed an update with a reference to one of the fixed issues.

**Comment by u2** [comment]
:smile: @jonas054  Thanks.

**Comment by u2** [comment]
@bradleypriest  The same for me.

**Comment by u2** [comment]
@bradleypriest  The same for me.

**Pull request merged**
