### PR TITLE
Drop Ruby 2.5 support

### PR DESCRIPTION
**Pull request by koic**
This includes the following changes:

## Require JRuby 9.3 or higher

CRuby 2.5 compatible JRuby 9.2 will be dropped and CRuby 2.6 compatible JRuby 9.3 or higher is required.

## Retire `Lint/UselessElse` cop

Ruby 2.6 does not support `begin` ... `else` syntax. So `Lint/UselessElse` can't work because it causes a parsing error.

NOTE: Some bugs found in RuboCop 1.28.1 have been fixed in the master branch. If the next version is a bug fix (i.e. 1.28.2), this PR would wait to be merged until the next minor release.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
Excellent PR! It shows you the nice progress that every Ruby release has made, given the many small improvements that are now possible in RuboCop's code. 🚀 

I was wondering for a bit i we shouldn't make `Lint/UselessElse` a no-op to reduce the likelihood of something breaking after this update, but I doubt anyone was disabling it, so the deletion should likely be fine.

**Comment by bbatsov** [comment]
(and I did cut 1.28.2 just before merging this PR)

**Comment by deivid-rodriguez** [comment]
Hi @koic, thanks for all the work here. Should the `Lint/UselessElseWithoutRescue` should also be restored, given that `TargetRubyVersion: 2.5` is back?

**Comment by koic** [comment]
@deivid-rodriguez Yup, I think so too! I've opened #10697 to restore the `Lint/UselessElseWithoutRescue` cop. Thank you!

**Pull request merged**
