### PR TITLE
Layout/ClassStructure fixes [wip]

### PR DESCRIPTION
**Pull request by marcandre**
This is a complete refactoring.

Bug fixes:

1) Correctly distinguishes private / protected / public, including constants and class methods
2) Offenses raised are now complete, accurate, and minimal [#9738]
3) `attr_accessor`/`writer`/`reader` and `initializer` will now default to `methods` if not specified in the order
4) All other known bugs are fixed

### CODE REVIEW

**Comment by nahaylo** [comment]
Hey @marcandre, it's almost a year since you've created this PR and no more movement there. How can I help you to finish it?

**Comment by marcandre** [comment]
@nahaylo Argh, this PR turned out to be more work than anticipated. I haven't worked on it in a while. I add a bit more work done locally; I rebased that and forced pushed, but I expect tests to fail. Are you willing to have a look at it? That would be sooo awesome.

**Comment by nahaylo** [comment]
@marcandre yes, I'll check failing tests and will create a PR with fixes (hope I can handle them).

**Comment by bbatsov** [comment]
I'm closing this PR due to no recent activity. Feel free to re-open it if you ever come back to it.

**Pull request closed without merging**
